CREATE TABLE STAGED_ORDERS (
    RegionIdentifier nvarchar(32),
    OrderIdentifier nvarchar(32),
	ServiceLocationIdentifier nvarchar(32),
    BeginDate date,
	QuantitySize1 float,
	QuantitySize2 float,
	QuantitySize3 float,
	PreferredRouteIdentifier nvarchar(32),
	OrginDepotIdentifier nvarchar(32),
	OrderClassIdentifier nvarchar(32),
	SpecialInstructions nvarchar(500),
	ServiceWindowOverride1Start time(7),
	ServiceWindowOverride1End time(7),
	ServiceWindowOverride2Start time(7),
	ServiceWindowOverride2End time(7),
	LiftgateOnly nvarchar(20),
	GuarenteedDelivery nvarchar(30),
	Avail nvarchar(7),
	"Delete" bit,
	Staged datetime2(7),
	Error nvarchar(MAX),
	"Status" nvarchar(50)
);